PM_USER: ENC[AES256_GCM,data:Xe9W2O7zhFT6C64ImWwTGC65,iv:rGKH4+f7QgXMLd1pe5mbpgt7SLaf51C+kkQG7M+lwWw=,tag:vMpQ0OmclLO5/4ob6p4BGA==,type:str]
PM_PASS: ENC[AES256_GCM,data:r41P2dY0EwM=,iv:VcHI7XUAluUAc7ctGF4h+/wbV3/GVY0FLYu83I19GIk=,tag:NpWBRcnAkUy1k5ZLCiEdyw==,type:str]
MINIO_USERNAME: ENC[AES256_GCM,data:LBInQveXxH94LQ==,iv:kB24aMW6/640pm0wzcTKGLnYGWKspVBMqT1qd+CB9aA=,tag:a2UKx9KBzHoTwTsjHLaxtg==,type:str]
MINIO_PASSWORD: ENC[AES256_GCM,data:BD8wB1soUYUEpKBQtg==,iv:9YVIs/vUgJ9yHznW+gaqLeIMfYt0xE4kunOojYhpbJE=,tag:cWyjDxQwAlUeK3qOPqLXBQ==,type:str]
AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3uiQdA==,iv:VCyGX77X0b78qnd8Q3T3s2W8U0Tt2v3EOJVpnnMUEts=,tag:GqCgdKlKklL1orHmXr4jFA==,type:str]
AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:tGxYgwP2SEIrmZqXjP9Qpr+X1Ene6ZhE,iv:dpkc29XJZePrHQYvm0qijgyBHz0IZ78mCeYMaCmP8BM=,tag:rocWMuNE2iZNKdpBpxXmBA==,type:str]
PROXMOX_VE_ENDPOINT: ENC[AES256_GCM,data:t3RdjzkpcwrXKcQKWgeq2+PDTbHwFW2QtEbqRaPfooc5Qw==,iv:p8I2yxalx/dV15T/GHbDxmyY2f30ZyZ8UVfjrMNRDYI=,tag:blj8qKGu56BYY0MNBkaLjA==,type:str]
PROXMOX_VE_API_TOKEN: ENC[AES256_GCM,data:KofwtBix/1EmTEkA0RA4z5M0jm09t0mfV56HUlK+dwgdAmQkdIy3iodxiN36Y2HQlhg=,iv:F9TbBAzx2FdeXdO6h1w7+VpjB6ok7UWzWZmyTrYrBcc=,tag:IndXdMaxIwifD97AWe4NPA==,type:str]
PROXMOX_VE_INSECURE: ENC[AES256_GCM,data:4bQU1A==,iv:1rM6lsbmGKHfv2VhLmNc0siAM0thc9BwetygzWlb+Yw=,tag:Us324WRaq4FL6oAGhhCk2Q==,type:bool]
PROXMOX_CONTAINER_PASSWORD: ENC[AES256_GCM,data:sqLy6zna1y8=,iv:fQhH74M2QMNdYG4qiX81egR2A0/8S26jJ18YB2k38Qg=,tag:vLqaTFwvgxG7mHWQqoEfHg==,type:str]
sops:
    age:
        - recipient: age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdGs3dnNRRGoxZ3NCZWxj
            cDIyV3BNZnRCSVBYQVZyKytmRTY0aXRXNFNFCkpVVWtjTXF1YW51Y2U2L0NIcnNw
            NldyWFBadFBhR2JZY2hJa3UxQlY3ZEUKLS0tIEZTa3REMEE1NFFQNHE2RXZRRmpU
            Q1FIempZanpZNlRkRHJaL2h3bXp2T0UKlkxqr7LfA0+aaqyx1RABVdQq4E+Jc/df
            uG1tJOs5A8VPTO+4/fy0U0U7worgZaCEIliBld0ecO2MYnfK78/NnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-04T09:10:39Z"
    mac: ENC[AES256_GCM,data:UxIHJ5asiy/0lnPYrDYQ7IcXxcdGpHRtrT3wueJFhoaAWBU741ribUUrMNU6clcSl3E+DyyYQQ6qEJdlVH92mDo8MEGLMkdr9bhuIALS1ZQtA+XqRfkk0Q9nTvTqEJRFKwWEWhLHC2xa9Ay5TO1OOgR1H9WPRNZ5SN7y7FjTqLE=,iv:wR7vfXWKMhSBiVU+w2V3+e6ioZ0467jwhQGD3eoGzIE=,tag:xJmwbYrTUXRZYlxyl8Jztg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
