repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: tofu-fmt
      - id: tofu-validate
      # - id: goimports

  - repo: local
    hooks:
      - id: check-staging-catalog-version
        name: staging catalog_version muss auf main-Branch "main" sein
        language: script
        entry: .hooks/check-staging-catalog-version.sh
        always_run: true
        pass_filenames: false
