providers:
  vault:
    kind: hashicorp
    options:
      address: https://vault.home.sflab.io:8200
    maps:
      - id: netbox_production
        path: secrets_homelab/netbox_production
        keys:
          api_token: NETBOX_API_TOKEN_PRODUCTION

      - id: netbox_staging
        path: secrets_homelab/netbox_staging
        keys:
          api_token: NETBOX_API_TOKEN_STAGING

      - id: technitium_tsig_key_name
        path: secrets_homelab/technitium
        keys:
          tsig_key_name: TECHNITIUM_TSIG_KEY_NAME
          tsig_key_secret: TECHNITIUM_TSIG_KEY_SECRET
