[tools]
"aqua:dagger" = "latest"
go = "1.26.3"
opentofu = "1.12.1"
terragrunt = "1.0.6"
mc = "latest"
vault = "1.21.1"
fnox = "latest"
pre-commit = "latest"

[plugins]
fnox-env = "https://github.com/jdx/mise-env-fnox"

[env]
PROJECT_NAME = "{{ config_root | basename }}"

VAULT_ADDR = "https://vault.home.sflab.io"
VAULT_SKIP_VERIFY = "true"
VAULT_TOKEN = "{{ exec(command='cat ~/.vault-token') }}"

_.file = [
  { path = "{{env.HOME}}/.env", optional = true },
  { path = ".env", optional = true },
  { path = ".creds.env.yaml" }
  # { path = ".creds.env.yaml", redact = true }
]
_.path = ["./scripts"]

_.fnox-env = { tools = true }

[hooks]
enter = { task = "hooks:enter" }
