[tools]
"aqua:dagger" = "latest"
go = "1.26.3"
opentofu = "1.12.1"
terragrunt = "1.0.6"
mc = "latest"
vault = "1.21.1"

[env]
PROJECT_NAME = "{{ config_root | basename }}"

_.file = [
  { path = "{{env.HOME}}/.env", optional = true },
  { path = ".env", optional = true },
  { path = ".creds.env.yaml" }
  # { path = ".creds.env.yaml", redact = true }
]
_.path = ["./scripts"]
_.source = "./scripts/load-vault-secrets.sh"

[hooks]
enter = [
  'echo "\n[MISE] Setup $PROJECT_NAME project..."',
  #
  'mise i -q',
  #
  'pre-commit install -f --hook-type pre-commit'
]
