#!/usr/bin/env bash

#MISE description="Applies the given Terragrunt stack."

#USAGE arg "<env>" help="The environment to use" default=""
#USAGE arg "<target>" help="The target unit" default=""
#USAGE flag "-d --dry-run" help="Show the commands without executing it"
#USAGE flag "-y --yes" help="Automatic yes to prompts" default="false"

#MISE raw=true

set -e

source "$MISE_CONFIG_ROOT/.mise/common.sh"

# check preconditions, REQUIRED_ENV_VARS default is defined in common.sh
# redefine the REQUIRED_ENV_VARS=("VAR_NAME_1" "VAR_NAME_2") to overwrite the default list if needed
checkEnvVars REQUIRED_ENV_VARS

if [[ -z "${usage_env:-}" ]]; then
  ENVIRONMENT=$(printf "staging\nproduction" | gum filter --fuzzy --placeholder "Select an environment:")
else
  ENVIRONMENT="${usage_env}"
fi
echo "Selected environment: $ENVIRONMENT"

cd "$MISE_CONFIG_ROOT/$ENVIRONMENT"

if [[ -z "${usage_target:-}" ]]; then
  stack_dirs=()

  while IFS= read -r -d '' dir; do
    stack_dirs+=("$(basename "$dir")")
  done < <(find "." -mindepth 1 -maxdepth 1 -type d -print0)

  SELECTED_STACK=$(printf "%s\n" "${stack_dirs[@]}" | gum filter --fuzzy --placeholder "Select a stack to operate on:")
else
  SELECTED_STACK="${usage_target}"
fi

cd "$MISE_CONFIG_ROOT/$ENVIRONMENT/$SELECTED_STACK"

CMD="terragrunt stack run apply --provider-cache"
if [ "${usage_yes:-false}" = "true" ]; then
  CMD+=" --non-interactive"
fi

echo ""
echo "🚀 Executing 'mise run terragrunt:stack:apply-old $ENVIRONMENT $SELECTED_STACK'"
echo "   Commands: $CMD"
echo "   Working dir: $(pwd)"
echo ""

if [ "${usage_dry_run:-false}" = "true" ]; then
  echo "Dry run mode. Command not executed."
  exit 0
fi

eval $CMD
