#!/usr/bin/env bash

#USAGE arg "<env>" help="The environment to use" default=""
#USAGE arg "<target>" help="The target unit" default=""
#USAGE flag "-d --dry-run" help="Show the commands without executing it"

#MISE raw=true

set -e

if [[ -z "${usage_env:-}" ]]; then
  ENVIRONMENT=$(gum choose "staging" "production")
else
  ENVIRONMENT="${usage_env}"
fi
echo "Selected environment: $ENVIRONMENT"

cd "$MISE_CONFIG_ROOT/$ENVIRONMENT"

if [[ -z "${usage_target:-}" ]]; then
  stack_dirs=()

  while IFS= read -r -d '' dir; do
    stack_dirs+=("$(basename "$dir")")
  done < <(find "." -mindepth 1 -maxdepth 1 -type d -print0)

  # Show a selection menu with gum to select a unit
  selected_stack=$(printf "%s\n" "${stack_dirs[@]}" | gum choose --header="Select a stack to operate on:")
else
  selected_stack+=("${usage_target}")
fi

cd "$MISE_CONFIG_ROOT/$ENVIRONMENT/$selected_stack"

CMD="terragrunt stack run destroy"

echo ""
echo "🚀 Executing..."
echo "   Commands: $CMD"
echo "   Working dir: $(pwd)"
echo ""

if [ "$usage_dry_run" = "true" ]; then
  echo "Dry run mode. Command not executed."
  exit 0
fi

echo "⚠️ Are you really sure to destroy the stack?"
read -p "Type 'do it baby' to confirm: " confirm

if [[ "$confirm" != "do it baby" ]]; then
  echo ""
  echo "Destroy aborted by user"
  exit 1
fi

eval $CMD
