#!/usr/bin/env bash

#MISE description="Destroys the given Terragrunt stack."

#USAGE arg "<env>" help="The environment to use" default=""
#USAGE arg "<target>" help="The target unit" default=""
#USAGE flag "-d --dry-run" help="Show the commands without executing it"
#USAGE flag "-y --yes" help="Automatic yes to prompts" default="false"

#MISE raw=true

set -e

source "$MISE_CONFIG_ROOT/.mise/common.sh"

# check preconditions, REQUIRED_ENV_VARS default is defined in common.sh
# redefine the REQUIRED_ENV_VARS=("VAR_NAME_1" "VAR_NAME_2") to overwrite the default list if needed
checkRequiredEnvVars REQUIRED_ENV_VARS
checkOptionalEnvVars OPTIONAL_ENV_VARS

ENVIRONMENT=$(selectEnvironment)

cd "$MISE_CONFIG_ROOT/$ENVIRONMENT"

SELECTED_STACK=$(selectStack)

cd "$MISE_CONFIG_ROOT/$ENVIRONMENT/$SELECTED_STACK"

CMD="terragrunt stack run destroy --provider-cache"
if [ "${usage_yes?}" = "true" ]; then
  CMD+=" --non-interactive"
fi

logCommand "$CMD" "$usage_dry_run"

eval $CMD
