#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

PROJECT_DIR="$SCRIPT_DIR/../../../.."

ENVIRONMENT=$(gum choose "staging" "production")
echo "Selected environment: $ENVIRONMENT"

cd "$PROJECT_DIR/$ENVIRONMENT"

stack_dirs=()
while IFS= read -r -d '' dir; do
  stack_dirs+=("$(basename "$dir")")
done < <(find "." -mindepth 1 -maxdepth 1 -type d -print0)

# Show a selection menu with gum to select a unit
selected_stack=$(printf "%s\n" "${stack_dirs[@]}" | gum choose --header="Select a stack to operate on:")

cd "$selected_stack"

TERRAGRUNT_STACK_DESTROY_CMD="terragrunt stack run destroy -- --auto-approve"

echo "Running: $TERRAGRUNT_STACK_DESTROY_CMD"
eval $TERRAGRUNT_STACK_DESTROY_CMD
