#!/usr/bin/env bash

#MISE description="Plans the given Terragrunt stack."

#USAGE arg "<env>" help="The environment to use" default=""
#USAGE arg "<target>" help="The target unit" default=""
#USAGE flag "-d --dry-run" help="Show the commands without executing it"

#MISE raw=true

set -e

source "$MISE_CONFIG_ROOT/.mise/common.sh"

# check preconditions, REQUIRED_ENV_VARS default is defined in common.sh
# redefine the REQUIRED_ENV_VARS=("VAR_NAME_1" "VAR_NAME_2") to overwrite the default list if needed
checkRequiredEnvVars REQUIRED_ENV_VARS
checkOptionalEnvVars OPTIONAL_ENV_VARS

ENVIRONMENT=$(selectEnvironment)

cd "$MISE_CONFIG_ROOT/$ENVIRONMENT"

SELECTED_STACK=$(selectStack)

CMD="dagger call --progress=plain plan \
  --source $MISE_CONFIG_ROOT \
  --stack-dir $ENVIRONMENT/$SELECTED_STACK \
  --ssh-socket=unix://$SSH_AUTH_SOCK \
  --env-vars AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
  --env-vars PROXMOX_VE_ENDPOINT=$PROXMOX_VE_ENDPOINT \
  --env-vars PROXMOX_VE_INSECURE=true \
  --env-vars AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
  --env-vars PROXMOX_VE_API_TOKEN=$PROXMOX_VE_API_TOKEN \
  --env-vars NETBOX_API_TOKEN=$NETBOX_API_TOKEN \
  --env-vars TSIG_KEY_SECRET=$TSIG_KEY_SECRET \
  --env-vars TSIG_KEY_NAME=$TSIG_KEY_NAME \
  --env-vars PROXMOX_CONTAINER_PASSWORD=$PROXMOX_CONTAINER_PASSWORD"

logCommand "$CMD" "$usage_dry_run"

eval $CMD
