#!/usr/bin/env bash

#MISE description="Plans the given Terragrunt stack."

#USAGE arg "<env>" help="The environment to use" default=""
#USAGE arg "<target>" help="The target unit" default=""
#USAGE flag "-d --dry-run" help="Show the commands without executing it"

#MISE raw=true

set -e

source "$MISE_CONFIG_ROOT/.mise/common.sh"

ENVIRONMENT=$(selectEnvironment)

cd "$MISE_CONFIG_ROOT/$ENVIRONMENT"

SELECTED_STACK=$(selectStack)

cd "$MISE_CONFIG_ROOT/$ENVIRONMENT/$SELECTED_STACK"

CMD="terragrunt stack run plan --provider-cache"

logCommand "$CMD" "$usage_dry_run"

eval $CMD
