#!/usr/bin/env bash

#MISE description="Plans the given Terragrunt stack."

#USAGE arg "<env>" help="The environment to use" default=""
#USAGE arg "<target>" help="The target unit" default=""
#USAGE flag "-d --dry-run" help="Show the commands without executing it"

#MISE raw=true

set -e

if [[ -z "${usage_env:-}" ]]; then
  ENVIRONMENT=$(printf "staging\nproduction" | gum filter --fuzzy --placeholder "Select an environment:")
else
  ENVIRONMENT="${usage_env}"
fi
echo "Selected environment: $ENVIRONMENT"

cd "$MISE_CONFIG_ROOT/$ENVIRONMENT"

if [[ -z "${usage_target:-}" ]]; then
  stack_dirs=()

  while IFS= read -r -d '' dir; do
    stack_dirs+=("$(basename "$dir")")
  done < <(find "." -mindepth 1 -maxdepth 1 -type d -print0)

  # Show a selection menu with gum to select a unit
  SELECTED_STACK=$(printf "%s\n" "${stack_dirs[@]}" | gum filter --fuzzy --placeholder "Select a stack to operate on:")
else
  SELECTED_STACK+=("${usage_target}")
fi

export TF_VAR_netbox_token="${NETBOX_API_TOKEN}"

CMD="dagger call plan \
  --source $MISE_CONFIG_ROOT \
  --stack-dir $ENVIRONMENT/$SELECTED_STACK \
  --ssh-socket=unix://$SSH_AUTH_SOCK \
  --env-vars AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
  --env-vars PROXMOX_VE_ENDPOINT=$PROXMOX_VE_ENDPOINT \
  --env-vars PROXMOX_VE_INSECURE=true \
  --env-vars AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
  --env-vars PROXMOX_VE_API_TOKEN=$PROXMOX_VE_API_TOKEN \
  --env-vars NETBOX_API_TOKEN=$NETBOX_API_TOKEN \
  --env-vars TF_VAR_netbox_token=$TF_VAR_netbox_token \
  --env-vars TF_VAR_dns_key_secret=$TF_VAR_dns_key_secret \
  --env-vars PROXMOX_CONTAINER_PASSWORD=$PROXMOX_CONTAINER_PASSWORD"

echo ""
echo "🚀 Executing 'mise run terragrunt:stack:plan $ENVIRONMENT $SELECTED_STACK'"
echo "   Commands: $CMD"
echo "   Working dir: $(pwd)"
echo ""

if [ "$usage_dry_run" = "true" ]; then
  echo "Dry run mode. Command not executed."
  exit 0
fi

eval $CMD
