#!/usr/bin/env bash

MINIO_HOST="minio.home.sflab.io"
MINIO_PORT="9000"

MINIO_ALIAS="myminio"
MINIO_BUCKET_NAME="staging-terragrunt-tfstates"

mc alias set $MINIO_ALIAS "http://${MINIO_HOST}:${MINIO_PORT}" $MINIO_USERNAME $MINIO_PASSWORD

echo ""
# check if service account already exists
if mc admin user svcacct list $MINIO_ALIAS $MINIO_USERNAME | grep -q "$AWS_ACCESS_KEY_ID"; then
  echo "Service account $AWS_ACCESS_KEY_ID already exists"
else
  echo "Creating service account $AWS_ACCESS_KEY_ID"

  mc admin user svcacct add $MINIO_ALIAS $MINIO_USERNAME --access-key "$AWS_ACCESS_KEY_ID" --secret-key "$AWS_SECRET_ACCESS_KEY"
fi

if mc ls $MINIO_ALIAS/$MINIO_BUCKET_NAME >/dev/null 2>&1; then
  echo "Bucket $MINIO_BUCKET_NAME already exists"
else
  echo "Creating bucket $MINIO_BUCKET_NAME"

  mc mb $MINIO_ALIAS/$MINIO_BUCKET_NAME

  mc version enable $MINIO_ALIAS/$MINIO_BUCKET_NAME
fi

echo ""
echo "Available MinIO Buckets:"
mc ls $MINIO_ALIAS
