#!/usr/bin/env bash

#MISE description="Hook task that runs on directory entry. Used to setup environment variables and other necessary configuration for the project."

echo "[MISE] Setup $PROJECT_NAME project..."

mise i -q

pre-commit install -f --hook-type pre-commit

mise run vault:create-token
